org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.99
mod_id=ufo
mod_name=UFO FUTURE
mod_license=LGPL-3.0-or-later for code; CC-BY-NC-SA-3.0 for art and texture assets
mod_version=2.1-fix7
mod_group_id=com.raishxn.ufo
mod_authors=Raishxn
mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.

ae2_version=26.1.10-beta
guideme_version=26.1.10-alpha
yoga_version=1.0.0
taffy_version=1.1.4
ae2addonlib_version=26.1.3-alpha

ldlib_file_id=7915945
glodium_file_id=5821676

jei_version=8747131
kubejs_file_id=5810100
rhino_file_id=5691686
applied_flux_file_id=7429565
mega_file_id=7952621

ex_pattern_file_id=7871693
ae2_jei_integration_file_id=5748513
mmmmmmmmmmmm_file_id=7206981
selene_file_id=7238829
advancedae_file_id=7849217
geckolib_version=5.5.2
ldlib2_version=26.1.2.37